2025-03-04 21:29:56,558 - INFO - Uploaded train dataset with size: (8693, 14)
2025-03-04 21:29:59,875 - INFO - Final preprocessed training dataset uploaded successfully'
2025-03-04 21:29:59,876 - INFO - Parameters optimization started
2025-03-04 21:30:01,575 - INFO - Best params: {'iterations': 24, 'depth': 3, 'learning_rate': 0.007561248757236054, 'l2_leaf_reg': 15.54947349895065}
2025-03-04 21:30:03,414 - INFO - Model saved in models/model.pkl
2025-03-04 21:30:05,114 - INFO - Best model uploaded in ClearML successfully
2025-03-04 21:30:05,118 - INFO - Accuracy on training data: 0.7185
2025-03-04 21:30:05,118 - INFO - Closing ClearML session
2025-03-04 21:31:18,067 - INFO - ClearML task initialized
2025-03-04 21:31:18,070 - INFO - Model successfully uploaded from models/model.pkl
2025-03-04 21:31:18,087 - INFO - Uploaded test dataset with size: (4277, 13)
2025-03-04 21:31:21,673 - INFO - Final test dataset uoloaded in ClearML as 'final_test_dataset'
2025-03-04 21:31:21,677 - INFO - Preductions completed
2025-03-04 21:31:21,683 - INFO - Predictions saved in data/results.csv
2025-03-04 21:31:29,436 - INFO - Prediction results uploaded in ClearML successfully
2025-03-04 23:11:31,359 - WARNING - Retrying (Retry(total=239, connect=240, read=239, redirect=240, status=240)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.clear.ml', port=443): Read timed out. (read timeout=3.0)")': /auth.login
2025-03-04 23:12:01,895 - INFO - Uploaded train dataset with size: (8693, 14)
2025-03-04 23:12:05,506 - INFO - Final preprocessed training dataset uploaded successfully
2025-03-04 23:12:05,506 - INFO - Parameters optimization started
2025-03-04 23:19:26,499 - INFO - Best params: {'iterations': 295, 'depth': 5, 'learning_rate': 0.05395838262039709, 'l2_leaf_reg': 1.1356294492631531}
2025-03-04 23:19:50,433 - INFO - Model saved in models/model.pkl
2025-03-04 23:19:52,260 - INFO - Best model uploaded in ClearML successfully
2025-03-04 23:19:52,276 - INFO - Accuracy on training data: 0.8360
2025-03-04 23:19:52,277 - INFO - Closing ClearML session
2025-03-05 00:38:32,005 - INFO - ClearML task initialized
2025-03-05 00:38:32,020 - INFO - Model successfully uploaded from models/model.pkl
2025-03-05 00:38:32,049 - INFO - Uploaded test dataset with size: (4277, 13)
2025-03-05 00:38:35,346 - INFO - Final test dataset uploaded in ClearML as 'final_test_dataset'
2025-03-05 00:38:35,347 - ERROR - Error during prediction CatBoostClassifier.predict() got an unexpected keyword argument 'cat_features'
2025-03-05 00:40:49,396 - INFO - ClearML task initialized
2025-03-05 00:40:49,399 - INFO - Model successfully uploaded from models/model.pkl
2025-03-05 00:40:49,409 - INFO - Uploaded test dataset with size: (4277, 13)
2025-03-05 00:40:52,731 - INFO - Final test dataset uploaded in ClearML as 'final_test_dataset'
2025-03-05 00:40:52,742 - INFO - Predictions completed
2025-03-05 00:40:52,745 - INFO - Predictions saved in data/results.csv
2025-03-05 00:40:55,947 - INFO - Prediction results uploaded in ClearML successfully
2025-03-05 03:57:39,877 - INFO - ClearML task initialized
2025-03-05 03:57:39,879 - ERROR - Model from models/model.pkl not found!
2025-03-05 03:57:39,880 - ERROR - Error during prediction Model from models/model.pkl not found!
2025-03-05 03:58:52,616 - INFO - ClearML task initialized
2025-03-05 03:58:52,619 - INFO - Model successfully uploaded from data/models/model.pkl
2025-03-05 03:58:52,630 - INFO - Uploaded test dataset with size: (4277, 13)
2025-03-05 03:58:56,475 - INFO - Final test dataset uploaded in ClearML as 'final_test_dataset'
2025-03-05 03:58:56,488 - INFO - Predictions completed
2025-03-05 03:58:56,493 - INFO - Predictions saved in data/results.csv
2025-03-05 03:59:00,451 - INFO - Prediction results uploaded in ClearML successfully
2025-03-05 04:02:35,729 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:02:36,425 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:08:58,048 - INFO - Uploaded train dataset with size: (8693, 14)
2025-03-05 04:09:00,833 - INFO - Final preprocessed training dataset uploaded successfully
2025-03-05 04:09:00,834 - INFO - Parameters optimization started
2025-03-05 04:10:24,250 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:12:00,713 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:12:06,170 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:12:06,673 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:12:06,834 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:12:07,009 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:12:07,144 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:10,759 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:15,809 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:16,326 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:16,487 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:16,664 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:16,833 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:16,984 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:17,139 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:41,703 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:42,363 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:14:42,894 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:20:14,691 - INFO - Uploaded train dataset with size: (8693, 14)
2025-03-05 04:20:16,969 - INFO - Final preprocessed training dataset uploaded successfully
2025-03-05 04:20:16,970 - INFO - Parameters optimization started
2025-03-05 04:20:22,718 - ERROR - Error during prediction Current task already created and requested task name 'Spaceship_Prediction' does not match current task name 'Spaceship_Training'. If you wish to create additional tasks use `Task.create`, or close the current task with `task.close()` before calling `Task.init(...)`
2025-03-05 04:26:14,290 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2025-03-05 04:26:14,300 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2025-03-05 04:27:17,332 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2025-03-05 04:27:17,342 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2025-03-10 07:31:35,507 - INFO - Uploaded train dataset with size: (8693, 14)
2025-03-10 07:31:38,539 - INFO - Final preprocessed training dataset uploaded successfully
2025-03-10 07:31:38,540 - INFO - Parameters optimization started
2025-03-10 07:37:36,890 - INFO - Best params: {'iterations': 272, 'depth': 4, 'learning_rate': 0.08572731060923496, 'l2_leaf_reg': 8.073931943472134}
2025-03-10 07:37:49,526 - INFO - Model saved in ../models/model.pkl
2025-03-10 07:37:50,564 - INFO - Best model uploaded in ClearML successfully
2025-03-10 07:37:50,586 - INFO - Accuracy on training data: 0.8304
2025-03-10 07:37:50,586 - INFO - Closing ClearML session
